version: '3'
services:
  backend:
    build: ./backend
    volumes:
        - "./backend/:/app/"
    ports:
     - "5000:5000"
  db:
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - TZ=${TZ}
    ports:
      - 13306:3306    
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/app/frontend/
    ports:
      - "3000:3000"
